# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: '@example-org/cspell-dict'
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/example-dict.dic.txt
    generateNonStrict: true

checksumFile: true
